name: build tippecanoe with gdal image

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-build-image:
    uses: airspace-link-inc/kube-gitops/.github/workflows/build-image.yaml@main
    with:
      dockerfile-path: ./Dockerfile_GDAL
      branch: ${{ github.ref }}
      image-name: felt/tippecanoe-gdal
      image-tag: ${{ github.sha }}
    secrets: inherit